# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on:
  push:
    branches:
      - "dev"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        run: |
          export CURRENT_DIR=`pwd`
          cd $CURRENT_DIR
          echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_ENV
          sudo apt install -y nodejs npm  && sudo pip install yq
          sudo npm install -g @angular/cli

      - name: Build
        run: |
          npm ci
          ng build --configuration production

      - name: Set develop dir
        run: |
          echo "DEPLOY_DIR=./www/domains/develop.selecro.cz" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/dev'

      - name: Set prod dir
        run: |
          echo "DEPLOY_DIR=./www/domains/selecro.cz" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: List Files in Distribution Directory
        run: ls -R ./dist

      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.CD_FTP_SERVER }}
          user: ${{ secrets.CD_FTP_USERNAME }}
          password: ${{ secrets.CD_FTP_PASSWORD }}
          local_dir: "./dist/webovky"
          remote_dir: ${{ env.DEPLOY_DIR }}
          delete: "false"
